version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - "9200:9200"

  mongo:
    image: mongo:3.4.3
    ports:
      - "27017:27017"

  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"

  redis:
    image: redis:3.0.7
    ports:
      - "6379:6379"
